import { getUserResponse } from '../api-message-class/message';


export const mockUserData: getUserResponse[] = [
    {
        userId: "1FA3282F-9366-4329-07B0-08D962C58BFF",
        name: "Ronald",
        surname: "Jones",
        email: "rj@gmail.com",
        password: "",
        phone: "0724918832",
        startDate: "2021-08-13",
        openForWork: false,
        userType: 0
    },
    {
        userId: "78E5E87D-A90F-497F-07B1-08D962C58BFF",
        name: "Mark",
        surname: "Smith",
        email: "m.smith@gmail.com",
        password: "",
        phone: "0624918732",
        startDate: "10-08-2021",
        openForWork: true,
        userType: 0
    },
    {
        userId: "E0DD2909-6390-4884-07B2-08D962C58BFF",
        name: "Sam",
        surname: "Kane",
        email: "sam.kane@gmail.com",
        password: "",
        phone: "0714316842",
        startDate: "16-08-2021",
        openForWork: false,
        userType: 0
    },
    {
        userId: "40E2DB56-3480-41E3-07B3-08D962C58BFF",
        name: "Judith",
        surname: "Polgar",
        email: "jud.polgar@gmail.com",
        password: "",
        phone: "0724918832",
        startDate: "13-08-2021",
        openForWork: false,
        userType: 0
    },
    {
        userId: "1761AE28-CD45-4CB7-07B4-08D962C58BFF",
        name: "Wesley",
        surname: "So",
        email: "so@gmail.com",
        password: "",
        phone: "0626914822",
        startDate: "07-08-2021",
        openForWork: true,
        userType: 0
    },
    {
        userId: "A94A834B-7874-417D-07B5-08D962C58BFF",
        name: "Magnus",
        surname: "Carlsen",
        email: "m.carlsen@gmail.com",
        password: "",
        phone: "0124938323",
        startDate: "12-06-2021",
        openForWork: true,
        userType: 0
    },
    {
        userId: "BE4084D0-AECE-4EF6-07B6-08D962C58BFF",
        name: "Fabiano",
        surname: "Caruana",
        email: "Caruana00@gmail.com",
        password: "",
        phone: "0784914831",
        startDate: "11-07-2021",
        openForWork: true,
        userType: 1
    },
    {
        userId: "7",
        name: "Alireza",
        surname: "Firouzja",
        email: "Alireza.f012@gmail.com",
        password: "",
        phone: "0736918831",
        startDate: "12-08-2021",
        openForWork: false,
        userType: 0
    },
    {
        userId: "8",
        name: "Jan Krystof",
        surname: "Duda",
        email: "JKD@yahoo.com",
        password: "",
        phone: "0724975834",
        startDate: "13-04-2021",
        openForWork: true,
        userType: 0
    },    {
        userId: "9",
        name: "Lilly",
        surname: "Allen",
        email: "L.Allen@gmail.com",
        password: "",
        phone: "0724213842",
        startDate: "13-09-2021",
        openForWork: false,
        userType: 0
    },
    {
        userId: "10",
        name: "Bobby fischer",
        surname: "Jones",
        email: "B.fischer00@gmail.com",
        password: "",
        phone: "0724712831",
        startDate: "13-06-2021",
        openForWork: true,
        userType: 0
    },
    {
        userId: "11",
        name: "Paul",
        surname: "Morphy",
        email: "Charles.Morphy@gmail.com",
        password: "",
        phone: "0154918532",
        startDate: "13-08-2021",
        openForWork: false,
        userType: 0
    },
    {
        userId: "12",
        name: "Adolf",
        surname: "Andersson",
        email: "Andersson@gmail.com",
        password: "",
        phone: "0724218330",
        startDate: "13-05-2021",
        openForWork: true,
        userType: 0
    },
    {
        userId: "13",
        name: "Mikhail",
        surname: "Tal",
        email: "Misha@gmail.com",
        password: "",
        phone: "0726918312",
        startDate: "23-06-2021",
        openForWork: true,
        userType: 0
    },
    {
        userId: "14",
        name: "Mark",
        surname: "Taimanov",
        email: "m.taimanov@gmail.com",
        password: "",
        phone: "0724311833",
        startDate: "13-05-2021",
        openForWork: true,
        userType: 1
    },
    {
        userId: "15",
        name: "Raul",
        surname: "Capablanca",
        email: "cuban@gmail.com",
        password: "",
        phone: "0734714832",
        startDate: "23-08-2021",
        openForWork: false,
        userType: 0
    },
    {
        userId: "16",
        name: "Frank",
        surname: "Marshall",
        email: "f.marshall00@gmail.com",
        password: "",
        phone: "0724918231",
        startDate: "30-08-2021",
        openForWork: false,
        userType: 0
    },
    {
        userId: "17",
        name: "Phillip",
        surname: "Kennedy",
        email: "phillip.kennedy@gmail.com",
        password: "",
        phone: "0774913831",
        startDate: "05-04-2021",
        openForWork: true,
        userType: 0
    },
    {
        userId: "18",
        name: "Patrick",
        surname: "Johnson",
        email: "johnson@gmail.com",
        password: "",
        phone: "0725918632",
        startDate: "16-03-2021",
        openForWork: true,
        userType: 0
    },
    {
        userId: "19",
        name: "Donald",
        surname: "Dickson",
        email: "dondickson09@gmail.com",
        password: "",
        phone: "0616126770",
        startDate: "15-07-2021",
        openForWork: true,
        userType: 0
    },
    {
        userId: "20",
        name: "Nick",
        surname: "Jackson",
        email: "N.jackson@gmail.com",
        password: "",
        phone: "0616726770",
        startDate: "30-06-2021",
        openForWork: true,
        userType: 0
    },
    {
        userId: "21",
        name: "James",
        surname: "May",
        email: "J.May@gmail.com",
        password: "",
        phone: "0724318532",
        startDate: "21-05-2021",
        openForWork: true,
        userType: 0
    },
    {
        userId: "22",
        name: "Nora",
        surname: "Allen",
        email: "Nora.Allen@gmail.com",
        password: "",
        phone: "0724618513",
        startDate: "16-05-2021",
        openForWork: true,
        userType: 3
    },
    {
        userId: "23",
        name: "Clark",
        surname: "Kent",
        email: "Superma@gmail.com",
        password: "",
        phone: "0724912812",
        startDate: "15-05-2021",
        openForWork: true,
        userType: 3
    },
    {
        userId: "24",
        name: "Lex",
        surname: "Luther",
        email: "L.Luther@gmail.com",
        password: "",
        phone: "0824914832",
        startDate: "21-06-2021",
        openForWork: true,
        userType: 1
    },
    {
        userId: "25",
        name: "Alexander",
        surname: "Alekhine",
        email: "Executioner@gmail.com",
        password: "",
        phone: "0824915832",
        startDate: "23-11-2021",
        openForWork: false,
        userType: 3
    },
    {
        userId: "26",
        name: "Paul",
        surname: "Keres",
        email: "Keres.P@gmail.com",
        password: "",
        phone: "0824318832",
        startDate: "01-08-2021",
        openForWork: true,
        userType: 2
    },
    {
        userId: "27",
        name: "Garry",
        surname: "Kasparov",
        email: "KasparovChess@gmail.com",
        password: "",
        phone: "0824668552",
        startDate: "13-03-2021",
        openForWork: true,
        userType: 2
    },
];